### ISSUE TITLE
dvidtools.set_param() requires "http://" for server string but example in docs omits it

### ISSUE THREAD

**Issue by olbris** [flyconnectome/dvid_tools#1]
The example docs at https://dvidtools.readthedocs.io/en/latest/ says (essentially):

`dt.set_param('127.0.0.1:8000', node, user)`

However, this will give you an error. server = 'http://127.0.0.1:8000' is required.

**Comment by schlegelp** [comment]
Hi & thanks for the report. 

Fixed with b7cc96d023a1cb24399ceb1d7cad36d9d01a48d2

Closing this issue as fixed.
